  version: '2'
  services:
    mysql:
      image: mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: devops
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
      ports:
        - "3307:3306"
    spring:
      image: devops_back
      build: ./
      restart: on-failure
      depends_on:
        - mysql
      ports:
        - "8082:8082"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD:

