  version: '2'
  services:
    mysql:
      image: mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: devops
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      ports:
        - "3306:3306"
    spring:
      image: devops_back
      build: ./
      restart: on-failure
      depends_on:
        - mysql
      ports:
        - "8082:8082"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD:

    angular:
      image: devops_front
      ports:
        - "4000:4000"
      depends_on:
        - spring
