  version: '2'
  services:
    mysql:
      image: mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: devops
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
      ports:
        - "3307:3306"
    spring:
      image: devops_back
      build: ./
      restart: on-failure
      depends_on:
        - mysql
      ports:
        - "8082:8082"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD:
    prometheus:
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus:/etc/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      networks:
        - monitoring-net

    grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ALLOW_EMBEDDING=true
        - GF_SECURITY_COOKIE_SECURE=false
      volumes:
        - ./grafana:/var/lib/grafana
      depends_on:
        - prometheus
      networks:
        - monitoring-net

  networks:
    monitoring-net:
      driver: bridge