  version: '2'
  services:
    mysql:
      image: mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: devops
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
    spring:
      image: spring
      build: ./
      restart: on-failure
      depends_on:
        - mysql
      ports:
        - "8082:8082"

    angular:
      image: angular
      ports:
        - "80:80"
      depends_on:
        - spring
