global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
        - targets: [ '10.0.2.15:8082' ]